import type { Unit } from '../../../types';

export const SPECIALTIES = ['Oncologia', 'Mastologia', 'Radiologia', 'Ginecologia'];

export const UNITS_DATA: Unit[] = [
  {
    id: 'unit-barretos',
    name: 'Hospital de Amor Barretos',
    city: 'Barretos',
    state: 'SP',
    lat: -20.557,
    lng: -48.5678,
    types: ['Prevenção', 'Tratamento', 'Reabilitação'],
    address: 'Rua Antenor Duarte Villela, 1331 - Dr. Paulo Prata',
    phone: '(17) 3321-6600',
    hours: 'Segunda a Sexta, 07:00 às 17:00',
    specialties: ['Oncologia', 'Mastologia', 'Radiologia', 'Ginecologia'],
  },
  {
    id: 'unit-lagarto',
    name: 'Hospital de Amor Lagarto',
    city: 'Lagarto',
    state: 'SE',
    lat: -10.9161,
    lng: -37.6534,
    types: ['Prevenção', 'Tratamento'],
    address: 'Rodovia Lourival Baptista, s/n - Centro',
    phone: '(79) 3631-9300',
    hours: 'Segunda a Sexta, 07:00 às 17:00',
    specialties: ['Mastologia', 'Ginecologia'],
  },
  {
    id: 'unit-portovelho',
    name: 'Hospital de Amor Amazônia',
    city: 'Porto Velho',
    state: 'RO',
    lat: -8.7612,
    lng: -63.9039,
    types: ['Prevenção', 'Tratamento', 'Reabilitação'],
    address: 'BR-364, Km 17 - Rural',
    phone: '(69) 3219-4900',
    hours: 'Segunda a Sexta, 07:00 às 17:00',
    specialties: ['Oncologia', 'Radiologia', 'Ginecologia'],
  },
  {
    id: 'unit-jales',
    name: 'Hospital de Amor Jales',
    city: 'Jales',
    state: 'SP',
    lat: -20.2689,
    lng: -50.5458,
    types: ['Tratamento'],
    address: 'Avenida Francisco Jalles, 3737 - Jardim Estados Unidos',
    phone: '(17) 3624-3900',
    hours: 'Segunda a Sexta, 07:00 às 17:00',
    specialties: ['Oncologia', 'Mastologia'],
  },
  {
    id: 'unit-fernandopolis',
    name: 'Hospital de Amor Fernandópolis',
    city: 'Fernandópolis',
    state: 'SP',
    lat: -20.2831,
    lng: -50.2475,
    types: ['Prevenção'],
    address: 'Avenida Litério Greco, 300 - Vila Neves',
    phone: '(17) 3465-4300',
    hours: 'Segunda a Sexta, 07:00 às 17:00',
    specialties: ['Mastologia', 'Ginecologia'],
  },
  {
    id: 'unit-palmas',
    name: 'Hospital de Amor Palmas',
    city: 'Palmas',
    state: 'TO',
    lat: -10.2128,
    lng: -48.3603,
    types: ['Prevenção', 'Tratamento'],
    address: 'Quadra Arso 111, Alameda 19, s/n - Plano Diretor Sul',
    phone: '(63) 3218-4900',
    hours: 'Segunda a Sexta, 07:00 às 17:00',
    specialties: ['Oncologia', 'Ginecologia'],
  },
  {
    id: 'unit-goiania',
    name: 'Hospital de Amor Goiânia',
    city: 'Goiânia',
    state: 'GO',
    lat: -16.6869,
    lng: -49.2648,
    types: ['Tratamento'],
    address: 'Avenida Leste-Oeste, 3212 - Setor Marechal Rondon',
    phone: '(62) 3416-2600',
    hours: 'Segunda a Sexta, 07:00 às 17:00',
    specialties: ['Oncologia', 'Radiologia'],
  },
  {
    id: 'unit-campogrande',
    name: 'Hospital de Amor Campo Grande',
    city: 'Campo Grande',
    state: 'MS',
    lat: -20.4697,
    lng: -54.6201,
    types: ['Prevenção'],
    address: 'Avenida Aero Clube, 140 - Vila Sobrinho',
    phone: '(67) 3304-6600',
    hours: 'Segunda a Sexta, 07:00 às 17:00',
    specialties: ['Mastologia', 'Radiologia'],
  },
  {
    id: 'unit-juazeiro',
    name: 'Hospital de Amor Juazeiro',
    city: 'Juazeiro',
    state: 'BA',
    lat: -9.4116,
    lng: -40.5034,
    types: ['Prevenção'],
    address: 'Rodovia Lomanto Júnior, s/n - João XXIII',
    phone: '(74) 3614-9100',
    hours: 'Segunda a Sexta, 07:00 às 17:00',
    specialties: ['Ginecologia'],
  },
  {
    id: 'unit-campinagrande',
    name: 'Hospital de Amor Campina Grande',
    city: 'Campina Grande',
    state: 'PB',
    lat: -7.2306,
    lng: -35.8811,
    types: ['Prevenção'],
    address: 'Ria Pedro I, 550 - Centro',
    phone: '(83) 3310-4400',
    hours: 'Segunda a Sexta, 07:00 às 17:00',
    specialties: ['Mastologia', 'Ginecologia'],
  },
  {
    id: 'unit-macapa',
    name: 'Hospital de Amor Macapá',
    city: 'Macapá',
    state: 'AP',
    lat: 0.0389,
    lng: -51.0664,
    types: ['Prevenção'],
    address: 'Rodovia Duca Serra, Km 4 - Cabralzinho',
    phone: '(96) 3131-2900',
    hours: 'Segunda a Sexta, 07:00 às 17:00',
    specialties: ['Mastologia'],
  },
  {
    id: 'unit-boavista',
    name: 'Hospital de Amor Boa Vista',
    city: 'Boa Vista',
    state: 'RR',
    lat: 2.8235,
    lng: -60.6758,
    types: ['Prevenção'],
    address: 'Avenida Via das Flores, 2035 - Pricumã',
    phone: '(95) 3621-1500',
    hours: 'Segunda a Sexta, 07:00 às 17:00',
    specialties: ['Ginecologia'],
  },
  {
    id: 'unit-riobranco',
    name: 'Hospital de Amor Rio Branco',
    city: 'Rio Branco',
    state: 'AC',
    lat: -9.9749,
    lng: -67.8076,
    types: ['Prevenção'],
    address: 'Via Verde, 120 - Distrito Industrial',
    phone: '(68) 3215-4600',
    hours: 'Segunda a Sexta, 07:00 às 17:00',
    specialties: ['Mastologia', 'Radiologia'],
  },
  {
    id: 'unit-araguaina',
    name: 'Hospital de Amor Araguaína',
    city: 'Araguaína',
    state: 'TO',
    lat: -7.1895,
    lng: -48.2078,
    types: ['Prevenção', 'Reabilitação'],
    address: 'Avenida Filadélfia, s/n - Setor Oeste',
    phone: '(63) 3411-8900',
    hours: 'Segunda a Sexta, 07:00 às 17:00',
    specialties: ['Oncologia', 'Mastologia'],
  },
  {
    id: 'unit-unai',
    name: 'Hospital de Amor Unaí',
    city: 'Unaí',
    state: 'MG',
    lat: -16.3575,
    lng: -46.9064,
    types: ['Prevenção'],
    address: 'Rua Prefeito João Costa, 450 - Centro',
    phone: '(38) 3677-7400',
    hours: 'Segunda a Sexta, 07:00 às 17:00',
    specialties: ['Ginecologia'],
  },
  {
    id: 'unit-patrocinio',
    name: 'Hospital de Amor Patrocínio',
    city: 'Patrocínio',
    state: 'MG',
    lat: -18.9431,
    lng: -46.9995,
    types: ['Prevenção'],
    address: 'Avenida João Alves do Nascimento, 1000 - Centro',
    phone: '(34) 3831-2900',
    hours: 'Segunda a Sexta, 07:00 às 17:00',
    specialties: ['Mastologia', 'Ginecologia'],
  },
];
